/// Extended fields for TreeEntry - to be added to tree_entry.dart
/// This file contains all new fields for the 20-group comprehensive assessment

// GROUP 3: Location & Site Context (NEW FIELDS)
// - siteType (String)
// - landUseZone (String)
// - soilType (String)
// - soilCompaction (String)
// - drainage (String)
// - siteSlope (String)
// - aspect (String)
// - proximityToBuildings (double)
// - proximityToServices (String)

// GROUP 5: Tree Health Assessment (ENHANCED)
// - vigorRating (String)
// - foliageDensity (String)
// - foliageColor (String)
// - diebackPercent (double)
// - stressIndicators (List<String>)
// - growthRate (String)
// - seasonalCondition (String)

// GROUP 6: Tree Structure (NEW)
// - crownForm (String)
// - crownDensity (String)
// - branchStructure (String)
// - trunkForm (String)
// - trunkLean (String)
// - leanDirection (String)
// - rootPlateCondition (String)
// - buttressRoots (bool)
// - surfaceRoots (bool)
// - includedBark (bool)
// - includedBarkLocation (String)
// - structuralDefects (List<String>)
// - structuralRating (String)

// GROUP 7: VTA (ENHANCED)
// - cavityPresent (bool)
// - cavitySize (String)
// - cavityLocation (String)
// - decayExtent (String)
// - decayType (String)
// - fungalFruitingBodies (bool)
// - fungalSpecies (String)
// - barkDamagePercent (double)
// - barkDamageType (List<String>)
// - cracksSplits (bool)
// - cracksSplitsLocation (String)
// - deadWoodPercent (double)
// - girdlingRoots (bool)
// - girdlingRootsSeverity (String)
// - rootDamage (bool)
// - rootDamageDescription (String)
// - mechanicalDamage (bool)
// - mechanicalDamageDescription (String)

// GROUP 8: QTRA (NEW)
// - qtraTargetType (String)
// - qtraTargetValue (String)
// - qtraOccupancyRate (String)
// - qtraImpactPotential (String)
// - qtraProbabilityOfFailure (double)
// - qtraProbabilityOfImpact (double)
// - qtraRiskOfHarm (double) // auto-calculated
// - qtraRiskRating (String) // auto-calculated

// GROUP 9: ISA Risk (CURRENT - already exists)
// Using existing fields: likelihoodOfFailure, likelihoodOfImpact, consequenceOfFailure, overallRiskRating

// GROUP 10: Protection Zones (ENHANCED)
// srz and nrz already exist
// - tpzArea (double) // auto-calculated
// - encroachmentPresent (bool)
// - encroachmentType (List<String>)
// - protectionMeasures (String)

// GROUP 11: Tree Impact Assessment (NEW)
// - developmentType (String)
// - constructionZoneDistance (double)
// - rootZoneEncroachmentPercent (double)
// - canopyEncroachmentPercent (double)
// - excavationImpact (String)
// - serviceInstallationImpact (bool)
// - serviceInstallationDescription (String)
// - demolitionImpact (bool)
// - demolitionDescription (String)
// - accessRouteImpact (bool)
// - accessRouteDescription (String)
// - impactRating (String)
// - mitigationMeasures (String)

// GROUP 12: Development Compliance (NEW)
// - planningPermitRequired (bool)
// - planningPermitNumber (String)
// - planningPermitStatus (String)
// - planningOverlay (String)
// - heritageOverlay (bool)
// - significantLandscapeOverlay (bool)
// - vegetationProtectionOverlay (bool)
// - localLawProtected (bool)
// - localLawReference (String)
// - as4970Compliant (bool)
// - arboristReportRequired (bool)
// - councilNotification (bool)
// - neighborNotification (bool)

// GROUP 13: Retention & Removal (ENHANCED)
// retentionValue already exists
// - retentionRecommendation (String)
// - retentionJustification (String)
// - removalJustification (String)
// - significance (String)
// - replantingRequired (bool)
// - replacementRatio (double)
// - offsetRequirements (String)

// GROUP 14: Management & Works (ENHANCED)
// recommendedWorks already exists
// - pruningType (List<String>)
// - pruningSpecification (String)
// - worksPriority (String)
// - worksTimeframe (String)
// - estimatedCostRange (String)
// - accessRequirements (List<String>)
// - arboristSupervisionRequired (bool)
// - treeProtectionMeasures (String)
// - postWorksMonitoring (bool)
// - postWorksMonitoringFrequency (String)
// - worksCompletionDate (DateTime?)
// - worksCompliance (bool)

// GROUP 15: Tree Valuation (NEW)
// - valuationMethod (String)
// - baseValue (double)
// - conditionFactor (double)
// - locationFactor (double)
// - contributionFactor (double)
// - totalValuation (double) // auto-calculated
// - valuationDate (DateTime?)
// - valuerName (String)

// GROUP 16: Ecological Value (ENHANCED)
// habitatValue already exists
// - wildlifeHabitatValue (String)
// - hollowBearingTree (bool)
// - nestingSites (bool)
// - nestingSpecies (String)
// - habitatFeatures (List<String>)
// - biodiversityValue (String)
// - indigenousSignificance (bool)
// - indigenousSignificanceDetails (String)
// - culturalHeritage (bool)
// - culturalHeritageDetails (String)
// - amenityValue (String)
// - shadeProvision (String)

// GROUP 17: Regulatory & Compliance (NEW)
// - stateSignificant (bool)
// - heritageListed (bool)
// - heritageReference (String)
// - significantTreeRegister (bool)
// - bushfireManagementOverlay (bool)
// - environmentalSignificanceOverlay (bool)
// - waterwayProtection (bool)
// - threatenedSpeciesHabitat (bool)
// - insuranceNotificationRequired (bool)
// - legalLiabilityAssessment (String)
// - complianceNotes (String)

// GROUP 18: Monitoring & Scheduling (NEW)
// - nextInspectionDate (DateTime?)
// - inspectionFrequency (String)
// - monitoringRequired (bool)
// - monitoringFocus (List<String>)
// - alertLevel (String)
// - followUpActions (String)
// - complianceCheckDate (DateTime?)
// - inspectionHistory (List<Map<String, dynamic>>)

// GROUP 19: Advanced Diagnostics (NEW)
// - resistographTest (bool)
// - resistographDate (DateTime?)
// - resistographResults (String)
// - sonicTomography (bool)
// - sonicTomographyDate (DateTime?)
// - sonicTomographyResults (String)
// - pullingTest (bool)
// - pullingTestDate (DateTime?)
// - pullingTestResults (String)
// - rootCollarExcavation (bool)
// - rootCollarFindings (String)
// - soilTesting (bool)
// - soilTestingResults (String)
// - pathologyReport (String)
// - diagnosticImages (List<String>)
// - specialistConsultant (String)
// - diagnosticSummary (String)

// GROUP 20: Inspector & Report Details (ENHANCED)
// inspectorName, inspectionDate already exist
// - inspectorQualifications (String)
// - inspectorCompany (String)
// - weatherConditions (String)
// - reportType (String)
// - reportReferenceNumber (String)
// - reportVersion (int)

/// Total new fields to add: ~150 additional fields
/// These will be added to TreeEntry model with proper Hive annotations
