// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXJtx-6F1lhbdNSEV8G38bAVHPWbdODU4',
    appId: '1:512062345870:web:5a0832241950935e77afdf',
    messagingSenderId: '512062345870',
    projectId: 'arborist-assistant',
    authDomain: 'arborist-assistant.firebaseapp.com',
    storageBucket: 'arborist-assistant.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg4Q5idhdzFcokXy_BsiAO3GK_FXzrdOA',
    appId: '1:512062345870:ios:b3796e11b9c0611477afdf',
    messagingSenderId: '512062345870',
    projectId: 'arborist-assistant',
    storageBucket: 'arborist-assistant.firebasestorage.app',
    iosClientId: '512062345870-arnnr4cn9gtv9gj4tsdjrtd63e1otu0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.arboristAssistant',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg4Q5idhdzFcokXy_BsiAO3GK_FXzrdOA',
    appId: '1:512062345870:ios:b3796e11b9c0611477afdf',
    messagingSenderId: '512062345870',
    projectId: 'arborist-assistant',
    storageBucket: 'arborist-assistant.firebasestorage.app',
    iosClientId: '512062345870-arnnr4cn9gtv9gj4tsdjrtd63e1otu0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.arboristAssistant',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKfzb5WiOMuRsFmuxlHS8c4q7Ufv1ufIU',
    appId: '1:512062345870:android:3555f403e8d596f177afdf',
    messagingSenderId: '512062345870',
    projectId: 'arborist-assistant',
    storageBucket: 'arborist-assistant.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXJtx-6F1lhbdNSEV8G38bAVHPWbdODU4',
    appId: '1:512062345870:web:f9eaa8f78afb7e4a77afdf',
    messagingSenderId: '512062345870',
    projectId: 'arborist-assistant',
    authDomain: 'arborist-assistant.firebaseapp.com',
    storageBucket: 'arborist-assistant.firebasestorage.app',
  );

}